INSERT INTO properties (
owner_id, 
title,
description,
thumbnail_photo_url,
cover_photo_url,
cost_per_night,
parking_spaces,
number_of_bathrooms,
number_of_bedrooms,
country,
street,
city,
province,
post_code,
active
) VALUES (
  1,
  'Cozy house',
  'description',
  'https://assets0.biggerpockets.com/uploads/wordpress_blog_post/image/9112/featured_pretty-home.jpg',
  'https://assets0.biggerpockets.com/uploads/wordpress_blog_post/image/9112/featured_pretty-home.jpg',
  8000,
  4,
  3,
  2,
  'Canada',
  'Dunbar',
  'Vancouver',
  'BC',
  'V6S 1C6',
  True
),
(
  2,
  'Fancy house',
  'description',
  'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
  'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
  12000,
  6,
  4,
  4,
  'Canada',
  'Broadway',
  'Vancouver',
  'BC',
  'V6S 1C6',
  True
),
(
  3,
  'Average house',
  'description',
  'https://www.houseincanada.ca/wp-content/uploads/2018/03/How-to-buy-a-house-in-Calgary-Home-Buying-Guide..jpg',
  'https://www.houseincanada.ca/wp-content/uploads/2018/03/How-to-buy-a-house-in-Calgary-Home-Buying-Guide..jpg',
  6000,
  4,
  2,
  2,
  'Canada',
  'Grandville',
  'Vancouver',
  'BC',
  'V6S 1C6',
  True
);